
kind: Service
apiVersion: v1
metadata:
  name: microservicio
  labels:
    app: microservicio
spec:
  type: NodePort
  selector:
    app: microservicio
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-docker
  labels:
    app: microservicio-docker
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservicio-docker
        octopusexport: OctopusExport
    spec:
      containers:
        - name: microservicio-docker
          image: armandosa/microservicio-docker
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
